version: "3.2"
services:
    bot:
        container_name: music-downloader-service
        image: 'shashankullas/music-downloader:1.0.1'
        restart: always
        env_file:
            - .env
        ports:
          - 8000:8000