version: "3.2"
services:
    music-downloader-service:
        container_name: music-downloader-service
        image: 'shashankullas/music-downloader:4.0.2'
        network_mode: host
        restart: always
        env_file:
            - .env
        healthcheck:
            test: ["CMD", "curl", "-f", "https://tunes.shankquest.org/liveness"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 10s
