version: "3.2"
services:
    music-downloader-service:
        container_name: music-downloader-service
        image: 'shashankullas/music-downloader:2.0.2'
        restart: always
        env_file:
            - .env
        ports:
          - 8000:8000